plots:
	python plot_tsne.py 14 &
	python plot_tsne.py 13 &
	python plot_tsne.py 12 &
	python plot_tsne.py 11 &
	python plot_tsne.py 10 &
	python plot_tsne.py 9 &
	python plot_tsne.py 8 &
	python plot_tsne.py 7 &
	python plot_tsne.py 6 &
	python plot_tsne.py 5 &
	python plot_tsne.py 4 &
